config:
  file:
    winPath: D:\liepin\file
    linuxPath: /home/liepin/file
    url: localhost:8080
    allowType: png,jpg,jpeg,gif,bmp,xlsx,xls,doc,docx

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://162.14.79.224:3306/liepin
      username: root
      password: mysql123
  redis:
    host: 127.0.0.1
    port: 6379
    #    username:
    #    password:
    database: 0

  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: guest
    password: guest